### ISSUE TITLE
Case sensitive and insensitive variable names

### ISSUE THREAD

**Issue by ArashPartow** [costika1234/geometric-inequality-checker#1]
With regards to the comment found here:

https://github.com/costika1234/triangle-inequality-checker/blob/master/include/aliases.hpp#L10

I don't believe that to be true anymore, have a review of the following bit of documentation:

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L4477

**Comment by costika1234** [comment]
Thanks for pointing that out! I didn't know you added this feature which is more than welcome. I removed my workaround as part of this commit: https://github.com/costika1234/triangle-inequality-checker/commit/c13a8e9eb29bf8fb9756b597898e32dc105710aa

Kudos for creating this lovely library! 👍 🔝

**Comment by ArashPartow** [comment]
yw! :D
