### ISSUE TITLE
Bug in Compiling

### ISSUE THREAD

**Issue by Grotex** [costika1234/geometric-inequality-checker#2]
Hi Constantin Mateescu
I am Grotex
You can see me in AOPS

I compile the project via the **make** command but get this:
`
g++ -std=c++11 -pthread -I./include -I./lib/exprtk src/generate_triangle_info.cpp -o bin/generate_triangle_info
/tmp/ccbGAJnV.o: In function `is_distance_between_remarkable_points(std::string const&)':
generate_triangle_info.cpp:(.text+0x7fe): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
generate_triangle_info.cpp:(.text+0x845): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
generate_triangle_info.cpp:(.text+0x85b): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
/tmp/ccbGAJnV.o: In function `get_vars_from_expression(std::string const&)':
generate_triangle_info.cpp:(.text+0x967): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
generate_triangle_info.cpp:(.text+0x980): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
generate_triangle_info.cpp:(.text+0x991): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
generate_triangle_info.cpp:(.text+0x9e2): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++()'
generate_triangle_info.cpp:(.text+0x9ee): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
generate_triangle_info.cpp:(.text+0xa04): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
/tmp/ccbGAJnV.o: In function `std::basic_string<char, std::char_traits<char>, std::allocator<char> > regex_replace_with_callback<__gnu_cxx::__normal_iterator<char const*, std::string>, std::regex_traits<char>, char, std::string (*)(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::string (*)(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&))':
generate_triangle_info.cpp:(.text._Z27regex_replace_with_callbackIN9__gnu_cxx17__normal_iteratorIPKcSsEESt12regex_traitsIcEcPFSsRKSt13match_resultsIS4_SaISt9sub_matchIS4_EEEEESbIT1_St11char_traitsISG_ESaISG_EET_SL_RKSt11basic_regexISG_T0_ET2_[_Z27regex_replace_with_callbackIN9__gnu_cxx17__normal_iteratorIPKcSsEESt12regex_traitsIcEcPFSsRKSt13match_resultsIS4_SaISt9sub_matchIS4_EEEEESbIT1_St11char_traitsISG_ESaISG_EET_SL_RKSt11basic_regexISG_T0_ET2_]+0xb6): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
generate_triangle_info.cpp:(.text._Z27regex_replace_with_callbackIN9__gnu_cxx17__normal_iteratorIPKcSsEESt12regex_traitsIcEcPFSsRKSt13match_resultsIS4_SaISt9sub_matchIS4_EEEEESbIT1_St11char_traitsISG_ESaISG_EET_SL_RKSt11basic_regexISG_T0_ET2_[_Z27regex_replace_with_callbackIN9__gnu_cxx17__normal_iteratorIPKcSsEESt12regex_traitsIcEcPFSsRKSt13match_resultsIS4_SaISt9sub_matchIS4_EEEEESbIT1_St11char_traitsISG_ESaISG_EET_SL_RKSt11basic_regexISG_T0_ET2_]+0xc5): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
generate_triangle_info.cpp:(.text._Z27regex_replace_with_callbackIN9__gnu_cxx17__normal_iteratorIPKcSsEESt12regex_traitsIcEcPFSsRKSt13match_resultsIS4_SaISt9sub_matchIS4_EEEEESbIT1_St11char_traitsISG_ESaISG_EET_SL_RKSt11basic_regexISG_T0_ET2_[_Z27regex_replace_with_callbackIN9__gnu_cxx17__normal_iteratorIPKcSsEESt12regex_traitsIcEcPFSsRKSt13match_resultsIS4_SaISt9sub_matchIS4_EEEEESbIT1_St11char_traitsISG_ESaISG_EET_SL_RKSt11basic_regexISG_T0_ET2_]+0xdb): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
generate_triangle_info.cpp:(.text._Z27regex_replace_with_callbackIN9__gnu_cxx17__normal_iteratorIPKcSsEESt12regex_traitsIcEcPFSsRKSt13match_resultsIS4_SaISt9sub_matchIS4_EEEEESbIT1_St11char_traitsISG_ESaISG_EET_SL_RKSt11basic_regexISG_T0_ET2_[_Z27regex_replace_with_callbackIN9__gnu_cxx17__normal_iteratorIPKcSsEESt12regex_traitsIcEcPFSsRKSt13match_resultsIS4_SaISt9sub_matchIS4_EEEEESbIT1_St11char_traitsISG_ESaISG_EET_SL_RKSt11basic_regexISG_T0_ET2_]+0xf4): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
/tmp/ccbGAJnV.o: In function `std::basic_string<char, std::char_traits<char>, std::allocator<char> > regex_replace_with_callback<__gnu_cxx::__normal_iterator<char const*, std::string>, std::regex_traits<char>, char, std::string (*)(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::string (*)(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&))::{lambda(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)#1} std::for_each<std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > regex_replace_with_callback<__gnu_cxx::__normal_iterator<char const*, std::string>, std::regex_traits<char>, char, std::string (*)(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::string (*)(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&))::{lambda(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)#1}>(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >, std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > regex_replace_with_callback<__gnu_cxx::__normal_iterator<char const*, std::string>, std::regex_traits<char>, char, std::string (*)(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::string (*)(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&))::{lambda(std::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)#1})':
generate_triangle_info.cpp:(.text._ZSt8for_eachISt14regex_iteratorIN9__gnu_cxx17__normal_iteratorIPKcSsEEcSt12regex_traitsIcEEZ27regex_replace_with_callbackIS5_S7_cPFSsRKSt13match_resultsIS5_SaISt9sub_matchIS5_EEEEESbIT1_St11char_traitsISJ_ESaISJ_EET_SO_RKSt11basic_regexISJ_T0_ET2_EUlSG_E_ESQ_SO_SO_SQ_[_ZSt8for_eachISt14regex_iteratorIN9__gnu_cxx17__normal_iteratorIPKcSsEEcSt12regex_traitsIcEEZ27regex_replace_with_callbackIS5_S7_cPFSsRKSt13match_resultsIS5_SaISt9sub_matchIS5_EEEEESbIT1_St11char_traitsISJ_ESaISJ_EET_SO_RKSt11basic_regexISJ_T0_ET2_EUlSG_E_ESQ_SO_SO_SQ_]+0x1e): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator*()'
generate_triangle_info.cpp:(.text._ZSt8for_eachISt14regex_iteratorIN9__gnu_cxx17__normal_iteratorIPKcSsEEcSt12regex_traitsIcEEZ27regex_replace_with_callbackIS5_S7_cPFSsRKSt13match_resultsIS5_SaISt9sub_matchIS5_EEEEESbIT1_St11char_traitsISJ_ESaISJ_EET_SO_RKSt11basic_regexISJ_T0_ET2_EUlSG_E_ESQ_SO_SO_SQ_[_ZSt8for_eachISt14regex_iteratorIN9__gnu_cxx17__normal_iteratorIPKcSsEEcSt12regex_traitsIcEEZ27regex_replace_with_callbackIS5_S7_cPFSsRKSt13match_resultsIS5_SaISt9sub_matchIS5_EEEEESbIT1_St11char_traitsISJ_ESaISJ_EET_SO_RKSt11basic_regexISJ_T0_ET2_EUlSG_E_ESQ_SO_SO_SQ_]+0x36): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++()'
generate_triangle_info.cpp:(.text._ZSt8for_eachISt14regex_iteratorIN9__gnu_cxx17__normal_iteratorIPKcSsEEcSt12regex_traitsIcEEZ27regex_replace_with_callbackIS5_S7_cPFSsRKSt13match_resultsIS5_SaISt9sub_matchIS5_EEEEESbIT1_St11char_traitsISJ_ESaISJ_EET_SO_RKSt11basic_regexISJ_T0_ET2_EUlSG_E_ESQ_SO_SO_SQ_[_ZSt8for_eachISt14regex_iteratorIN9__gnu_cxx17__normal_iteratorIPKcSsEEcSt12regex_traitsIcEEZ27regex_replace_with_callbackIS5_S7_cPFSsRKSt13match_resultsIS5_SaISt9sub_matchIS5_EEEEESbIT1_St11char_traitsISJ_ESaISJ_EET_SO_RKSt11basic_regexISJ_T0_ET2_EUlSG_E_ESQ_SO_SO_SQ_]+0x49): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
collect2: error: ld returned 1 exit status
make: *** [generate_triangle_info] Error 1
`
How to fix the bug?
Pre-thanks.
Grotex

**Comment by costika1234** [comment]
According to https://stackoverflow.com/questions/8561850/compile-stdregex-iterator-with-gcc it looks like you are using an older version of `gcc`. You should be using at least version 5, which on Ubuntu Linux you can update like so:

`sudo apt-get install -qq g++-5`
`sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90`

Hope this helps!

**Comment by Grotex** [comment]
@costika1234 
Thanks my problem is broken
Grotex
