### ISSUE TITLE
Bug in Compiling 2

### ISSUE THREAD

**Issue by Grotex** [costika1234/geometric-inequality-checker#3]
Hi Constantin Mateescu

I compile the project(in msys2) via the make command but get this:
g++ -std=c++11 -pthread -I./include -I./lib/exprtk src/generate_triangle_info.cpp -o bin/generate_triangle_info
In file included from src/generate_triangle_info.cpp:7:
./include/utils.hpp: In function ‘long_d convert_radians_to_degrees(long_d)’:
./include/utils.hpp:324:37: error: ‘M_PI’ was not declared in this scope
  324 |     return angle_in_radians * 180 / M_PI;
      |                                     ^~~~
./include/utils.hpp: In function ‘long_d convert_degrees_to_radians(long_d)’:
./include/utils.hpp:329:31: error: ‘M_PI’ was not declared in this scope
  329 |     return angle_in_degrees * M_PI / 180;
      |                               ^~~~
make: *** [Makefile:36: generate_triangle_info] Error 1

How to fix the bug?
Pre-thanks.
Grotex

**Comment by Grotex** [comment]
error: ‘M_PI’ was not declared in this scope

what is that?

**Comment by costika1234** [comment]
Hi Grotex! Your compiler is unable to locate `M_PI` (the constant representing the number pi). I am not getting that error when compiling the project using `clang++` on macOS, so I would suggest checking out the following link: https://stackoverflow.com/questions/1727881/how-to-use-the-pi-constant-in-c. 

It looks like you only need to add 
```
#define _USE_MATH_DEFINES
```
just before `#include <cmath>` in `utils.hpp`. 

Hope this helps!

**Comment by Grotex** [comment]
Thanks!
